# -*- coding: utf-8 -*-
"""API NYT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-OV4DXJyRKz8JT4qLPZxdDFwDejZ4tu
"""

import requests
import pandas as pd
import time
from google.colab import files

# --- CONFIGURACIÓN SENIOR ---
API_KEY = "V9AaG98bMVzkN21ytyA9Icw3KEnVb6Jbzw6G0RlxDuvC6Yjb"
AÑO = 2025
MESES = range(1, 13) # Cobertura total del año

#EXTRACCION DE DATOS
def descargar_archivo_mensual(api_key, year, month):
    url = f"https://api.nytimes.com/svc/archive/v1/{year}/{month}.json?api-key={api_key}"
    print(f"📡 Recuperando inventario total de: {year}-{month:02d}...")

    try:
        response = requests.get(url)
        if response.status_code == 200:
            return response.json()['response']['docs']
        else:
            print(f"⚠️ Error {response.status_code} en mes {month}. Verifique API Key.")
            return []
    except Exception as e:
        print(f"❌ Error de conexión: {e}")
        return []

##FILTRADO POLITOLOGICO Y MINERIA DE TEXTO
def filtrar_por_peru(documentos):
    noticias_filtradas = []

    for doc in documentos:
        titular = doc.get('headline', {}).get('main', '')
        descripcion = doc.get('abstract') or doc.get('snippet', '')
        # Extraemos etiquetas oficiales del NYT
        # Manejar el caso donde 'keywords' podría ser None
        raw_keywords = doc.get('keywords')
        processed_keywords = raw_keywords if raw_keywords is not None else []
        keywords = [k['value'].lower() for k in processed_keywords]

        # Filtro de seguridad: captura variaciones semánticas
        if 'peru' in titular.lower() or 'peru' in descripcion.lower() or 'peru' in keywords:
            noticias_filtradas.append({
                "Fecha_Publicacion": doc.get('pub_date')[:10],
                "Titular_Noticia": titular,
                "Descripcion_Breve": descripcion,
                "Seccion_NYT": doc.get('section_name'),
                "Tipo_Material": doc.get('type_of_material'),
                "Keywords_Oficiales": ", ".join([k['value'] for k in processed_keywords]),
                "URL_Articulo": doc.get('web_url')
            })
    return noticias_filtradas

#EJECUCION. PROCESAMIENTO Y DESCARGA ACADEMICA
# --- INICIO DEL PROCESO ANUAL ---
corpus_peru_2025 = []
articulos_totales_procesados = 0

for mes in MESES:
    # 1. Traer todo el mes
    total_docs_mes = descargar_archivo_mensual(API_KEY, AÑO, mes)
    articulos_totales_procesados += len(total_docs_mes)

    # 2. Filtrar lo relevante para Perú
    filtrados = filtrar_por_peru(total_docs_mes)
    corpus_peru_2025.extend(filtrados)

    # 3. Rate Limit: Pausa de 12 segundos entre meses (Seguridad API)
    time.sleep(12)

# --- CONSOLIDACIÓN Y EXPORTACIÓN ---
if corpus_peru_2025:
    df_final = pd.DataFrame(corpus_peru_2025)

    # Ordenar cronológicamente (Enero -> Diciembre)
    df_final['Fecha_Publicacion'] = pd.to_datetime(df_final['Fecha_Publicacion'])
    df_final = df_final.sort_values(by='Fecha_Publicacion')

    nombre_file = f"NYT_Peru_2025_Analisis_Politologico.xlsx"
    df_final.to_excel(nombre_file, index=False)

    print("\n" + "="*40)
    print(f"📊 RESUMEN DE LA INVESTIGACIÓN:")
    print(f"   - Artículos del NYT analizados: {articulos_totales_procesados}")
    print(f"   - Noticias filtradas sobre Perú: {len(df_final)}")
    print("="*40)

    # DESCARGA AUTOMÁTICA
    print(f"📥 Descargando '{nombre_file}' a tu equipo...")
    files.download(nombre_file)
else:
    print("❌ No se encontraron registros de Perú en el archivo 2025 del NYT.")